pp_serverport: 5432
pp_servicename: postgresql-10
#pp_servicename: postgresql-11

rpm_url: https://packagecloud.io/install/repositories/citusdata/community/script.rpm.sh
#rpm_url: https://install.citusdata.com/community/rpm.sh   # newer url

citus_pkgs:
# - citus72_10
  - citus80_11        # Citus v8 - PostgreSQL v11

pp_shared_preload_libraries: citus
citus_memory_limit_service: MemoryMax
citus_nofile_limit: "infinity"

# Replication user
replication_user: replication
replication_password: replication
